spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwtauth
    username: appadmin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 2D4A404E635266556A586E3272357538782F413F4428472B4B6250645367566B
      expiration: 60000
      refresh-token:
        expiration: 604800000 # 7 days